### ISSUE TITLE
ERROR: Unable to find method 'com.android.build.gradle.internal.variant.BaseVariantData.getVariantDslInfo()Lcom/android/build/gradle/internal/core/VariantDslInfo;'.

### ISSUE THREAD

**Issue by rahuljain88** [Archinamon/android-gradle-aspectj#120]
I am using Archinamon( com.archinamon:android-gradle-aspectj:4.2.0 ),Android gradle version ( com.android.tools.build:gradle:3.6.2) and distributionUrl (https\://services.gradle.org/distributions/gradle-6.1-all.zip).

Getting below error 
ERROR: Unable to find method 'com.android.build.gradle.internal.variant.BaseVariantData.getVariantDslInfo()Lcom/android/build/gradle/internal/core/VariantDslInfo;'.
Possible causes for this unexpected error include:

**Comment by davidwong** [comment]
I think com.archinamon:android-gradle-aspectj:4.2.x was updated to be compatible with AGP 4.0, so probably won't work with 3.6.2.

**Comment by rahuljain88** [comment]
Thanks David it's works fine with gradle 4.0+

But when i use gradle version 3.6+ and archinamon version is 4.1.0 , still app is crashing with below error 

java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/appcompat/R$drawable;

any update on this ?
